# Copyright 2026 Hewlett Packard Enterprise Development LP
---
name: unit-tests

'on':
  pull_request:

jobs:
  jenkins-library-guard-unit-test:
    name: Jenkins @Library guard unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run Jenkins @Library guard unit test
        run: ./tests/guard-jenkins-library-pin-test.sh
