# Copyright 2026 Hewlett Packard Enterprise Development LP
---
name: unit-tests

'on':
  pull_request:

jobs:
  jenkins-library-guard-unit-test:
    name: Jenkins @Library guard unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run Jenkins @Library guard unit test
        run: ./tests/guard-jenkins-library-pin-test.sh
